#!/bin/bash

pandoc README.md -o index.html --toc --toc-depth=2 --template=index.revealjs

for mdfile in `ls _contents`; do
    pandoc "_contents/$mdfile" -o "contents/${mdfile%.md}.html" -t revealjs -s --template=slide.revealjs
done

# git add *
# git commit -m"update contents $1"
# git push origin gh-pages